/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;
import model.Livro;
import model.Movimentacao;
import util.arquivo;

/**
 *
 * @author Gabriel
 */
public class telaBiblioteca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaBiblioteca.class.getName());

    /**
     * Creates new form telas
     */
    
    List<Livro> listaLivros = new ArrayList<>();
    List<Categoria> listaCategorias = new ArrayList<>();
    List<Movimentacao> listaMovimentacoes = new ArrayList<>();

    public telaBiblioteca() {
        initComponents();
        setLocationRelativeTo(null);
        carregarDadosIniciais(); 
    }

    private int gerarNovoIdLivro() {
        int max = 0;
        for(Livro l : listaLivros) {
            if(l.getId() > max) max = l.getId();
        }
        return max + 1;
    }
    
    private int gerarNovoIdCategoria() {
        int max = 0;
        for(Categoria c : listaCategorias) {
            if(c.getId() > max) max = c.getId();
        }
        return max + 1;
    }
    
    private void carregarDadosIniciais() {
        try {
            listaCategorias.clear();
            listaLivros.clear();
            listaMovimentacoes.clear();
            
            jComboBoxCategorias.removeAllItems();

            List<String> linhasCat = arquivo.ler("categorias.txt");
            for (String linha : linhasCat) {
                String[] partes = linha.split(";");
                if(partes.length >= 2) { 
                    listaCategorias.add(new Categoria(Integer.parseInt(partes[0]), partes[1]));
                    jComboBoxCategorias.addItem(partes[0] + " - " + partes[1]);
                }
            }
            
            List<String> linhasLiv = arquivo.ler("livros.txt");
            for (String linha : linhasLiv) {
                String[] partes = linha.split(";");
                if(partes.length >= 6) {
                    listaLivros.add(new Livro(Integer.parseInt(partes[0]), partes[1], partes[2], 
                            Integer.parseInt(partes[3]), Integer.parseInt(partes[4]), partes[5]));
                }
            }
            atualizarTabelaLivros();

            List<String> linhasMov = arquivo.ler("movimentacoes.txt");
            for (String linha : linhasMov) {
                String[] partes = linha.split(";");
                if(partes.length >= 6) {
                    listaMovimentacoes.add(new Movimentacao(Integer.parseInt(partes[0]), 
                            Integer.parseInt(partes[1]), partes[2], partes[3], partes[4], partes[5]));
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados! Verifique os arquivos.");
        }
    }

    private void salvarAlteracoesLivros() {
        List<String> linhas = new ArrayList<>();
        for (Livro l : listaLivros) {
            linhas.add(l.toLinhaArquivo());
        }
        arquivo.reescreverArquivo("livros.txt", linhas);
    }

    private void atualizarTabelaLivros() {
        DefaultTableModel model = (DefaultTableModel) jTableLivros.getModel();
        model.setRowCount(0); // Limpa as linhas
        for (Livro l : listaLivros) {
            model.addRow(new Object[]{l.getId(), l.getTitulo(), l.getStatus()}); // Exibe ID, Título e Status
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMovimentacao = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFIDLivro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFNomeLocatario = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTFObservacoes = new javax.swing.JTextField();
        jButtonRegistrarMovimentacoes = new javax.swing.JButton();
        JPanelRelatorios = new javax.swing.JPanel();
        jComboBoxRelatorios = new javax.swing.JComboBox<>();
        jButtonGerarRelatorio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTARelatorio = new javax.swing.JTextArea();
        jPnaelCadastros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCategoria = new javax.swing.JTextField();
        jButtonSalvarCategoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFTituloLivro = new javax.swing.JTextField();
        jTFAutorLivro = new javax.swing.JTextField();
        jTFAnoLivro = new javax.swing.JTextField();
        jComboBoxCategorias = new javax.swing.JComboBox<>();
        jButtonCadastrarLivro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jTFBusca = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonEditarLivro = new javax.swing.JButton();
        jButtonEditarCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMovimentacao.setBackground(new java.awt.Color(204, 204, 204));
        jPanelMovimentacao.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(" ID dolivro:");
        jLabel5.setOpaque(true);

        jTFIDLivro.setBackground(new java.awt.Color(153, 153, 153));
        jTFIDLivro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(" Nome do locatário:");
        jLabel6.setOpaque(true);

        jTFNomeLocatario.setBackground(new java.awt.Color(153, 153, 153));
        jTFNomeLocatario.setForeground(new java.awt.Color(0, 0, 0));

        jComboBox1.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empréstimo", "Devolução", "Perda", "Danificado" }));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" Observações:");
        jLabel7.setOpaque(true);

        jTFObservacoes.setBackground(new java.awt.Color(153, 153, 153));
        jTFObservacoes.setForeground(new java.awt.Color(0, 0, 0));

        jButtonRegistrarMovimentacoes.setBackground(new java.awt.Color(153, 153, 153));
        jButtonRegistrarMovimentacoes.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistrarMovimentacoes.setText("Registrar");
        jButtonRegistrarMovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarMovimentacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMovimentacaoLayout = new javax.swing.GroupLayout(jPanelMovimentacao);
        jPanelMovimentacao.setLayout(jPanelMovimentacaoLayout);
        jPanelMovimentacaoLayout.setHorizontalGroup(
            jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMovimentacaoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrarMovimentacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMovimentacaoLayout.createSequentialGroup()
                        .addGroup(jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFIDLivro)
                            .addComponent(jTFNomeLocatario)
                            .addComponent(jTFObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelMovimentacaoLayout.setVerticalGroup(
            jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMovimentacaoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFIDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNomeLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMovimentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarMovimentacoes)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Movimentações", jPanelMovimentacao);

        JPanelRelatorios.setBackground(new java.awt.Color(204, 204, 204));

        jComboBoxRelatorios.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxRelatorios.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxRelatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livros Disponíveis", "Histórico de Livro", "Empréstimos no Mês", "Livros Mais Emprestados", "Livros Perdidos/Danificados", "Empréstimos por Categoria." }));

        jButtonGerarRelatorio.setBackground(new java.awt.Color(153, 153, 153));
        jButtonGerarRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGerarRelatorio.setText("Gerar Relatório");
        jButtonGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatorioActionPerformed(evt);
            }
        });

        jTARelatorio.setBackground(new java.awt.Color(153, 153, 153));
        jTARelatorio.setColumns(20);
        jTARelatorio.setForeground(new java.awt.Color(0, 0, 0));
        jTARelatorio.setRows(5);
        jScrollPane2.setViewportView(jTARelatorio);

        javax.swing.GroupLayout JPanelRelatoriosLayout = new javax.swing.GroupLayout(JPanelRelatorios);
        JPanelRelatorios.setLayout(JPanelRelatoriosLayout);
        JPanelRelatoriosLayout.setHorizontalGroup(
            JPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRelatoriosLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(JPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        JPanelRelatoriosLayout.setVerticalGroup(
            JPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelRelatoriosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jComboBoxRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGerarRelatorio)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatórios", JPanelRelatorios);

        jPnaelCadastros.setBackground(new java.awt.Color(153, 153, 153));
        jPnaelCadastros.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Nova Categoria:");
        jLabel1.setOpaque(true);

        jTFCategoria.setBackground(new java.awt.Color(153, 153, 153));
        jTFCategoria.setForeground(new java.awt.Color(0, 0, 0));

        jButtonSalvarCategoria.setBackground(new java.awt.Color(153, 153, 153));
        jButtonSalvarCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalvarCategoria.setText("Salvar Categoria");
        jButtonSalvarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCategoriaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Título do  livro:");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Autor(a):");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ano de publicação:");
        jLabel4.setOpaque(true);

        jTFTituloLivro.setBackground(new java.awt.Color(153, 153, 153));
        jTFTituloLivro.setForeground(new java.awt.Color(0, 0, 0));
        jTFTituloLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTituloLivroActionPerformed(evt);
            }
        });

        jTFAutorLivro.setBackground(new java.awt.Color(153, 153, 153));
        jTFAutorLivro.setForeground(new java.awt.Color(0, 0, 0));
        jTFAutorLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAutorLivroActionPerformed(evt);
            }
        });

        jTFAnoLivro.setBackground(new java.awt.Color(153, 153, 153));
        jTFAnoLivro.setForeground(new java.awt.Color(0, 0, 0));
        jTFAnoLivro.setOpaque(true);
        jTFAnoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAnoLivroActionPerformed(evt);
            }
        });

        jComboBoxCategorias.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxCategorias.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriasActionPerformed(evt);
            }
        });

        jButtonCadastrarLivro.setBackground(new java.awt.Color(153, 153, 153));
        jButtonCadastrarLivro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrarLivro.setText("Cadastrar livro");
        jButtonCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarLivroActionPerformed(evt);
            }
        });

        jTableLivros.setBackground(new java.awt.Color(153, 153, 153));
        jTableLivros.setForeground(new java.awt.Color(0, 0, 0));
        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Título", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLivros);

        jTFBusca.setBackground(new java.awt.Color(153, 153, 153));
        jTFBusca.setForeground(new java.awt.Color(0, 0, 0));
        jTFBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFBuscaActionPerformed(evt);
            }
        });

        jButtonPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonEditarLivro.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEditarLivro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarLivro.setText("Editar Livro");
        jButtonEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarLivroActionPerformed(evt);
            }
        });

        jButtonEditarCategoria.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEditarCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEditarCategoria.setText("Editar Categoria");
        jButtonEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnaelCadastrosLayout = new javax.swing.GroupLayout(jPnaelCadastros);
        jPnaelCadastros.setLayout(jPnaelCadastrosLayout);
        jPnaelCadastrosLayout.setHorizontalGroup(
            jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnaelCadastrosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnaelCadastrosLayout.createSequentialGroup()
                        .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFCategoria)
                                .addComponent(jTFTituloLivro)
                                .addComponent(jTFAutorLivro)
                                .addComponent(jTFAnoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jButtonCadastrarLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSalvarCategoria)))
                    .addGroup(jPnaelCadastrosLayout.createSequentialGroup()
                        .addComponent(jTFBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnaelCadastrosLayout.createSequentialGroup()
                        .addComponent(jButtonEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPnaelCadastrosLayout.setVerticalGroup(
            jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnaelCadastrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addGap(18, 18, 18)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTituloLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFAnoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarLivro)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPnaelCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarLivro)
                    .addComponent(jButtonEditarCategoria))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastros", jPnaelCadastros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCategoriaActionPerformed
        // TODO add your handling code here:
        if (jTFCategoria.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome da categoria obrigatório!");
            return;
        }
        
        int novoId = gerarNovoIdCategoria();
        Categoria novaCat = new Categoria(novoId, jTFCategoria.getText());
        
        listaCategorias.add(novaCat);
        arquivo.escrever("categorias.txt", novaCat.toString());
        
        jComboBoxCategorias.addItem(novoId + " - " + novaCat.getDescricao());
        JOptionPane.showMessageDialog(this, "Categoria salva!");
        jTFCategoria.setText("");
 
    }//GEN-LAST:event_jButtonSalvarCategoriaActionPerformed

    private void jTFTituloLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTituloLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTituloLivroActionPerformed

    private void jTFAutorLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAutorLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAutorLivroActionPerformed

    private void jTFAnoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAnoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAnoLivroActionPerformed

    private void jComboBoxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriasActionPerformed

    private void jTFBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFBuscaActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarLivroActionPerformed
        // TODO add your handling code here:
        int row = jTableLivros.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um livro na tabela!");
            return;
        }

        int id = Integer.parseInt(jTableLivros.getValueAt(row, 0).toString()); //Pega ID da tabela e busca o  Livro
        Livro livroEdit = null;
        for (Livro l : listaLivros) {
            if (l.getId() == id) {
                livroEdit = l;
            }
        }

        if (livroEdit != null) {
            String t = JOptionPane.showInputDialog("Novo Título:", livroEdit.getTitulo());
            String a = JOptionPane.showInputDialog("Novo Autor:", livroEdit.getAutor());
            if (t != null && !t.isEmpty() && a != null && !a.isEmpty()) {
                livroEdit.setTitulo(t);
                livroEdit.setAutor(a);
                salvarAlteracoesLivros();
                atualizarTabelaLivros();
            }
        }

    }//GEN-LAST:event_jButtonEditarLivroActionPerformed

    private void jButtonCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarLivroActionPerformed
           // TODO add your handling code here:
           try {
           if (jTFTituloLivro.getText().isEmpty() || jTFAutorLivro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha Título e Autor.");
                return;
            }
            if (jComboBoxCategorias.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Cadastre uma categoria antes!");
                return;
            }
            String titulo = jTFTituloLivro.getText();
            String autor = jTFAutorLivro.getText();
            int ano;
            try {
                ano = Integer.parseInt(jTFAnoLivro.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ano inválido! Digite apenas números.");
                return;
            }
            String catSel = (String) jComboBoxCategorias.getSelectedItem();
            int idCat = Integer.parseInt(catSel.split(" - ")[0]);

            int novoId = gerarNovoIdLivro();
            Livro novoLivro = new Livro(novoId, titulo, autor, idCat, ano, "Disponível");

            listaLivros.add(novoLivro);
            arquivo.escrever("livros.txt", novoLivro.toLinhaArquivo());
            atualizarTabelaLivros();
            JOptionPane.showMessageDialog(this, "Livro salvo!");

            jTFTituloLivro.setText("");
            jTFAutorLivro.setText("");
            jTFAnoLivro.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado. Verifique os dados.");
        }
    
    }//GEN-LAST:event_jButtonCadastrarLivroActionPerformed

    private void jButtonRegistrarMovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarMovimentacoesActionPerformed
        // TODO add your handling code here:
        try {
            int idLivro;
            try {
                idLivro = Integer.parseInt(jTFIDLivro.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID do Livro deve ser numérico!");
                return;
            }

            String responsavel = jTFNomeLocatario.getText();
            if (responsavel.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Digite o responsável!");
                return;
            }

            String tipo = (String) jComboBox1.getSelectedItem();
            String obs = jTFObservacoes.getText().isEmpty() ? "-" : jTFObservacoes.getText();

            Livro livroAlvo = null;
            for (Livro l : listaLivros) {
                if (l.getId() == idLivro) {
                    livroAlvo = l;
                }
            }

            if (livroAlvo == null) {
                JOptionPane.showMessageDialog(this, "Livro ID " + idLivro + " não encontrado!");
                return;
            }

            if (tipo.equals("Empréstimo")) {
                if (!livroAlvo.getStatus().equals("Disponível")) {
                    JOptionPane.showMessageDialog(this, "Livro indisponível!");
                    return;
                }
                livroAlvo.setStatus("Emprestado");
            } 
            else {
                if (tipo.equals("Devolução")) {
                livroAlvo.setStatus("Disponível");
                }
                else {
                    if (tipo.equals("Perda")) {
                    livroAlvo.setStatus("Perdido");
                    } 
                    else {
                        if (tipo.equals("Danificado")) {
                        livroAlvo.setStatus("Danificado");
                        }
                    }
                }
            }

            int idMov = listaMovimentacoes.size() + 1;// Cria e salva a movimentação do histórico
            String data = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            Movimentacao mov = new Movimentacao(idMov, idLivro, tipo, responsavel, data, obs);

            listaMovimentacoes.add(mov);
            arquivo.escrever("movimentacoes.txt", mov.toLinhaArquivo());

            salvarAlteracoesLivros();
            atualizarTabelaLivros();
            JOptionPane.showMessageDialog(this, "Movimentação registrada!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado. Verifique os dados.");
        }
    }//GEN-LAST:event_jButtonRegistrarMovimentacoesActionPerformed

    private void jButtonEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCategoriaActionPerformed
        // TODO add your handling code here:
        String idTxt = JOptionPane.showInputDialog("Digite o ID da Categoria para editar:");
        if (idTxt != null) {
            try {
                int id = Integer.parseInt(idTxt);
                Categoria catEdit = null;

                for (Categoria c : listaCategorias) {
                    if (c.getId() == id) {
                        catEdit = c;
                    }
                }

                if (catEdit != null) {
                    String novaDesc = JOptionPane.showInputDialog("Nova Descrição:", catEdit.getDescricao());
                    if (novaDesc != null && !novaDesc.isEmpty()) {
                        catEdit.setDescricao(novaDesc);

                        List<String> linhas = new ArrayList<>();
                        for (Categoria c : listaCategorias) {
                            linhas.add(c.toString());
                        }
                        arquivo.reescreverArquivo("categorias.txt", linhas);

                        jComboBoxCategorias.removeAllItems();
                        for (Categoria c : listaCategorias) {
                            jComboBoxCategorias.addItem(c.getId() + " - " + c.getDescricao());
                        }

                        JOptionPane.showMessageDialog(this, "Categoria Editada com sucesso!");
                    }
                } 
                else {
                    JOptionPane.showMessageDialog(this, "ID não encontrado.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID inválido! Digite um número inteiro.");
            }
        }
    }//GEN-LAST:event_jButtonEditarCategoriaActionPerformed

    private void jButtonGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatorioActionPerformed
        // TODO add your handling code here:
        int tipo = jComboBoxRelatorios.getSelectedIndex();
        jTARelatorio.setText(""); // Limpa a área de texto
        StringBuilder sb = new StringBuilder();

        if (tipo == 0) { //Livros Disponíveis
            sb.append("=== LIVROS DISPONÍVEIS ===\n");
            for (Livro l : listaLivros) {
                if (l.getStatus().equals("Disponível")) {
                    sb.append(l.getTitulo()).append("\n");
                }
            }
        }
        else if (tipo == 1) {  //Histórico de um Livro Específico
            String idTxt = JOptionPane.showInputDialog("ID do Livro:");
            if (idTxt != null) {
                try {
                    int id = Integer.parseInt(idTxt);
                    sb.append("HISTÓRICO DO LIVRO ID ").append(id).append(":\n");
                    for (Movimentacao m : listaMovimentacoes) {
                        if (m.getIdLivro() == id) {
                            sb.append(" - ").append(m.getData()).append(": ").append(m.getTipo())
                                    .append(" (Resp: ").append(m.getResponsavel()).append(")\n");
                        }
                    }
                } catch (NumberFormatException e) {
                    sb.append("ID Inválido.");
                }
            }
        } 
        else if (tipo == 2) { //3. Empréstimos no Mês
            String mes = JOptionPane.showInputDialog("Mês/Ano (ex: 11/2024):");
            if (mes != null && !mes.isEmpty()) {
                int count = 0;
                for (Movimentacao m : listaMovimentacoes) {
                    if (m.getTipo().equals("Empréstimo") && m.getData().contains(mes)) {
                        count++;
                    }
                }
                sb.append("Total de Empréstimos em ").append(mes).append(": ").append(count);
            }
        } 
        else if (tipo == 3) { //Livros Mais Emprestados Por Ano
            String ano = JOptionPane.showInputDialog("Digite o Ano (ex: 2024):");
            if (ano != null && !ano.isEmpty()) {
                sb.append("=== LIVROS MAIS EMPRESTADOS EM ").append(ano).append(" ===\n");
                for (Livro l : listaLivros) {
                    int qtd = 0;
                    for (Movimentacao m : listaMovimentacoes) {
                        if (m.getIdLivro() == l.getId()
                                && m.getTipo().equals("Empréstimo")
                                && m.getData().endsWith(ano)) {
                            qtd++;
                        }
                    }
                    if (qtd > 0) {
                        sb.append(l.getTitulo()).append(": ").append(qtd).append(" vezes\n");
                    }
                }
            }
        } 
        else if (tipo == 4) { // Perdidos ou Danificados
            sb.append("=== PERDIDOS OU DANIFICADOS ===\n");
            for (Livro l : listaLivros) {
                if (l.getStatus().equals("Perdido") || l.getStatus().equals("Danificado")) {
                    sb.append(l.getTitulo()).append(" - Status: ").append(l.getStatus()).append("\n");
                }
            }
        } 
        else if (tipo == 5) { //Empréstimos Por Categoria
            sb.append("=== EMPRÉSTIMOS POR CATEGORIA ===\n");
            for (Categoria c : listaCategorias) {
                int count = 0;
                for (Movimentacao m : listaMovimentacoes) {
                    if (m.getTipo().equals("Empréstimo")) {
                        for (Livro l : listaLivros) {
                            if (l.getId() == m.getIdLivro() && l.getIdCategoria() == c.getId()) {
                                count++;
                            }
                        }
                    }
                }
                sb.append(c.getDescricao()).append(": ").append(count).append(" empréstimos\n");
            }
        }
        jTARelatorio.setText(sb.toString());

    }//GEN-LAST:event_jButtonGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelRelatorios;
    private javax.swing.JButton jButtonCadastrarLivro;
    private javax.swing.JButton jButtonEditarCategoria;
    private javax.swing.JButton jButtonEditarLivro;
    private javax.swing.JButton jButtonGerarRelatorio;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRegistrarMovimentacoes;
    private javax.swing.JButton jButtonSalvarCategoria;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxCategorias;
    private javax.swing.JComboBox<String> jComboBoxRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelMovimentacao;
    private javax.swing.JPanel jPnaelCadastros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTARelatorio;
    private javax.swing.JTextField jTFAnoLivro;
    private javax.swing.JTextField jTFAutorLivro;
    private javax.swing.JTextField jTFBusca;
    private javax.swing.JTextField jTFCategoria;
    private javax.swing.JTextField jTFIDLivro;
    private javax.swing.JTextField jTFNomeLocatario;
    private javax.swing.JTextField jTFObservacoes;
    private javax.swing.JTextField jTFTituloLivro;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableLivros;
    // End of variables declaration//GEN-END:variables
}

